allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-brand@0.1.5-alpha.1'
  - '@deepseek-ai/dsh-client-connection@0.1.5-alpha.1'
  - '@deepseek-ai/dsh-credentials@0.1.5-alpha.1'
  - '@deepseek-ai/dsh-host-webserver@0.1.5-alpha.1'
